backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://i1.wp.com/www.devilswerk.com/wp-content/uploads/brizy/imgs/image1-1-221x48x0x4x221x41x1545528033.jpeg?w=930&ssl=1

media_folder: 'public/images/blog'
public_folder: '/images/blog'
media_library:
  name: cloudinary
  config:
    cloud_name: de7gc35gz
    api_key: 145971518884253

collections:
  - name: 'inventory'
    label: 'Inventory'
    folder: 'src/inventory'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Wheel Name', name: 'wheelName', widget: 'string' }
      - { label: 'Wheel Price', name: 'wheelPrice', widget: 'number' }
      - { label: 'Wheel Size', name: 'wheelSize', widget: 'string' }
      - { label: 'Store Image', name: 'image', widget: 'image' }
      - { label: 'Extra Images', name: 'extraImage', widget: 'image', allow_multiple: true, media_library: { config: { multiple: true, max_files: 10 } }, required: false }
      - { label: 'Condition', name: 'condition', widget: 'string' }
      - { label: 'Brand/Model', name: 'brandModel', widget: 'string' }
      - { label: 'Bolt Pattern', name: 'boltPattern', widget: 'string'}
      - { label: 'Front', name: 'front', widget: 'string' }
      - { label: 'Rear', name: 'rear', widget: 'string' }
      - { label: 'Color Face', name: 'colorFace', widget: 'string' }