backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://i1.wp.com/www.devilswerk.com/wp-content/uploads/brizy/imgs/image1-1-221x48x0x4x221x41x1545528033.jpeg?w=930&ssl=1

media_folder: 'public/images/blog'
public_folder: '/images/blog'

collections:
  - name: 'inventory'
    label: 'Inventory'
    folder: 'src/inventory'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Page-Name-with-dashes-only', name: 'pageName', widget: 'string' }
      - { label: 'Wheel Name', name: 'wheelName', widget: 'string' }
      - { label: 'Wheel Price', name: 'wheelPrice', widget: 'number' }
      - { label: 'Wheel Size (17in, 18in, 19in, 20in or Accessories)', name: 'wheelSize', widget: 'string' }
      - { label: 'Front Image', name: 'image', widget: 'image' }
      - { label: 'Extra Image1', name: 'extraImage1', widget: 'image' }
      - { label: 'Extra Image2', name: 'extraImage2', widget: 'image' }
      - { label: 'Extra Image3', name: 'extraImage3', widget: 'image' }
      - { label: 'Extra Image4', name: 'extraImage4', widget: 'image' }
      - { label: 'Extra Image5', name: 'extraImage5', widget: 'image' }
      - { label: 'Extra Image6', name: 'extraImage6', widget: 'image' }
      - { label: 'Extra Image7', name: 'extraImage7', widget: 'image' }
      - { label: 'Extra Image8', name: 'extraImage8', widget: 'image' }
      - { label: 'Extra Image9', name: 'extraImage9', widget: 'image' }
      - { label: 'Condition', name: 'condition', widget: 'string' }
      - { label: 'Brand/Model', name: 'brandModel', widget: 'string' }
      - { label: 'Bolt Pattern', name: 'boltPattern', widget: 'string'}
      - { label: 'Front', name: 'front', widget: 'string' }
      - { label: 'Rear', name: 'rear', widget: 'string' }
      - { label: 'Color Face', name: 'colorFace', widget: 'string' }